# Generated by Django 6.0.3 on 2026-03-22 12:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otptoken',
            name='otp_code',
        ),
        migrations.AddField(
            model_name='otptoken',
            name='otp',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login'), ('register', 'Register'), ('reset', 'Reset')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='trust_score',
            field=models.IntegerField(default=0),
        ),
    ]
