# Generated by Django 6.0.3 on 2026-03-21 13:52

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymedia',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='properties/'),
        ),
        migrations.AlterField(
            model_name='propertymedia',
            name='media_category',
            field=models.CharField(choices=[('room', 'Room'), ('kitchen', 'Kitchen'), ('bathroom', 'Bathroom'), ('outside', 'Outside'), ('other', 'Other')], default='room', max_length=30),
        ),
        migrations.AlterField(
            model_name='propertymedia',
            name='media_type',
            field=models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], default='photo', max_length=10),
        ),
    ]
